assert()
arrayOf()
arrayListOf<>()
arrayOfNulls<>()
uintArrayOf()
buildMap<>()
byteArrayOf()
booleanArrayOf()
buildList<>()
buildSet<>()
buildString()
compareBy<>()
charArrayOf()
charset()
check()
checkNotNull()
compareByDescending<>()
compareValues()
compareValuesBy()
doubleArrayOf()
error()
equals()
emptyList<>()
emptyArray<>()
emptyMap<>()
emptySequence<>()
emptySet<>()
enumValueOf<>()
enumValues<>()
floatArrayOf()
generateSequence()
hashSetOf<>()
hashCode()
hashMapOf<Int,String>()
intArrayOf()
iterator<Int> {  }
listOf()
SlidingWindowKt.checkWindowSizeStep
kotlin.doubleToUInt
UArraySortingKt.sortArray
AbstractMap.access
ListBuilderKt.arrayOfUninitializedElements
AbstractList.checkBoundsIndexes
AbstractMap.entryEquals
AbstractList.orderedHashCode$kotlin_stdlib
kotlin.createFailure
kotlin.uintRemainder
kotlin.TODO()
linkedMapOf()
linkedSetOf()
listOfNotNull()
longArrayOf()
kotlin.ulongDivide()
kotlin.ulongDivide-eb3DHEI(long, long)
kotlin.uintCompare(int, int)
mapOf()
mutableMapOf<>()
mutableListOf()
mutableSetOf()
nullsLast<>()
nullsFirst<>()
naturalOrder<>()
println()
print()
readln()
run {  }
runCatching {  }
TODO()
kotlin.emptyArray()