modLoader = "javafml"
loaderVersion = "[47,)"
license="MIT"
[[mods]]
modId="kotlinscript"
version="0.1.6"
displayName="Scripting Host"
description='''
A host mod for running Kotlin Scripts.
'''

# Optional metadata
authors="zodd"
credits="Powered by Kotlin and Minecraft Forge"
[[dependencies.kotlinscript]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"