modLoader="kotlinforforge" #mandatory
loaderVersion="[5.3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU-3"
issueTrackerURL=""

[[mods]] #mandatory
modId="kotlinscript" #mandatory
version="${version}" #mandatory
displayName="KotlinScript" #mandatory
displayURL=""
credits=""
authors="Liopyu"
description='''

'''

[[mixins]]
config = "mixins.kotlin-neoforge.json"
[[mixins]]
config = "mixins.kotlin-common.json"

[[dependencies.kotlinscript]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"

[[dependencies.kotlinscript]]
modId="neoforge" #mandatory
mandatory=true #mandatory
versionRange="[21,)" #mandatory